CREATE DATABASE `vsoteamroom` /*!40100 COLLATE 'utf8_general_ci' */

CREATE USER 'vso'@'localhost' IDENTIFIED BY 'vso';
GRANT USAGE ON *.* TO 'vso'@'localhost';
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `vsoteamroom`.* TO 'vso'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;